### PR TITLE
Remove commands pointing to non-existing artifacts

### PR DESCRIPTION
**Pull request by smolafilip**
Remove commands that tried to install non-existing artifacts

### CODE REVIEW

**Comment by siepkes** [comment]
Could you rebase your commits on a new branch which is up to date with master? I'm now seeing all previous commits which have already been merged.

**Comment by siepkes** [comment]
Almost there! ;-) rebase seems to have gone ok but you need to modify the commit message to describe what we are actually intending to do. The current commit message seems to be of the previous pull request (ie. doesn't describe what actually happens in this commit).

**Comment by Kortanul** [comment]
@siepkes wanna take another look at this?

**Review by siepkes — APPROVED** [review]
LGTM; I've verified these scripts no longer complain about missing files.

**Comment by siepkes** [comment]
Sorry this PR fell of my radar. Reviewed and merged!

**Pull request merged**
